import { type Paste, type Group } from "@prisma/client";
import type { NextPage } from "next";
import { type Session } from "next-auth";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { trpc } from "../../utils/trpc";

const Group: NextPage = () => {
  const { query, push } = useRouter();
  const id = query.id;

  const { data, status } = useSession();

  if (!id || typeof id !== "string") return <div>Please pass a valid id</div>;

  if (status === "loading") {
    return <div>Loading...</div>;
  }

  if (!data) {
    push("/api/auth/signin");
    return <></>;
  }

  return <GroupCheck id={id} session={data} />;
};

const GroupCheck: React.FC<{ id: string; session: Session }> = ({
  id,
  session,
}) => {
  const { push } = useRouter();

  const { isLoading, data } = trpc.group.getByIdWhereUser.useQuery({
    groupId: id,
  });

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (!data) {
    push("/");
    return <></>;
  }

  return <GroupContent session={session} group={data} />;
};

const GroupContent: React.FC<{
  session: Session;
  group: Group;
}> = ({ session, group }) => {
  const [pastes, setPastes] = useState<Paste[]>();

  const addPaste = trpc.group.addPaste.useMutation();

  useEffect(() => {
    const handlePaste = (event: any) => {
      event.preventDefault();
      const paste: string = event.clipboardData.getData("text");

      if (paste !== "") addPaste.mutate({ content: paste, groupId: group.id });
      console.log(paste);
    };

    window.addEventListener("paste", handlePaste);

    return () => {
      window.removeEventListener("paste", handlePaste);
    };
  });

  const { isLoading, data } = trpc.group.getPastes.useQuery(
    {
      groupId: group.id,
    },
    {
      onSuccess(data) {
        setPastes(data);
      },
    }
  );

  console.log(data);

  if (isLoading || !data || !pastes) return <div>Loading...</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1>Pastes in {group.name}</h1>
        {pastes.length > 0 ? (
          pastes
            .sort((x, y) => {
              return x.created_at < y.created_at ? 1 : -1;
            })
            .map((p) => {
              return (
                <div
                  key={p.id}
                  className={
                    p.created_by_id === session.user?.id ? "bg-slate-400" : ""
                  }
                  onClick={() => {
                    navigator.clipboard.writeText(p.content);
                  }}
                >
                  {p.content}
                </div>
              );
            })
        ) : (
          <div>There are no pastes yet. Be the first to create one!</div>
        )}
      </main>
    </>
  );
};

export default Group;
